### PR TITLE
SDK-80 Add suppport for springreload

### PR DESCRIPTION
**Pull request by rkorytkowski**
The pull request introduces the following changes:
- Changes container from Jetty to Tomcat
- Container is by default started in a forked process when calling openmrs-sdk:run, it gives us control over jvm settings such as memory, remote debug mode, springloaded agent and more...
- You can disable forking by setting -Dfork=false

### CODE REVIEW

**Comment by rkorytkowski** [comment]
@PawelGutkowski, would you mind reviewing?

**Comment by pgutkowski** [comment]
@rkorytkowski sure, I will take a look!

**Comment by pgutkowski** [comment]
Code looks great, I see You cleaned up a little mess left after SDK-91 too, but Adam and I are experiencing some minor problems when running servers after this commit:
- when rendering JSP, server throws this error: http://pastebin.com/HmbSHndD multiple times, we didn't find out the reason yet,
- ~~when debugging 'run' with fork mode in IntelliJ, after terminating the process, server is still up, forked process is not stopped~~ I've found out that's IntelliJ problem, when stop is triggered it just kills current process, doesn't exit it gracefully.

**Comment by rkorytkowski** [comment]
Yeah for your second bullet see http://stackoverflow.com/a/4727696, however I'll have to look at how is maven-jetty-plugin implemented, because even killing the process kills the server.

What version of OpenMRS are you running for the first error to appear? I've only tested with 1.11.5 and I don't see such an error. Is it a particular page or any page?

**Comment by pgutkowski** [comment]
I tested it a little bit more, it seems that error is thrown every time I enter Open Web App: manage Apps page, or Concept Dictionary OWA. I managed to trigger similiar error with more specific informations http://pastebin.com/xRZAJyKT seems like there's some dependency conflict issue

**Comment by rkorytkowski** [comment]
Okay, that's helpful. It's some classloading issues within jsp compiler.

**Pull request merged**
